version: 2.1
jobs:
    build:
        docker:
            - image: jhipster/jhipster:v7.0.1
        steps:
            - checkout
            - setup_remote_docker:
                version: 19.03.13
            - run:
                name: Install docker and docker-compose
                command: |
                    echo jhipster | sudo -S apt update
                    echo jhipster | sudo -S apt install -y docker.io
                    echo jhipster | sudo -S curl -Lo /usr/local/bin/docker-compose $(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep "browser_download_url.*docker-compose-Linux" | cut -d ':' -f 2,3 | tr -d \" | tr -d ' ')
                    echo jhipster | sudo -S chmod +x /usr/local/bin/docker-compose
                    docker version
                    docker-compose version
            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "package-lock.json" }}
                    # Perform a Partial Cache Restore (https://circleci.com/docs/2.0/caching/#restoring-cache)
                    - v1-dependencies-
            - run:
                name: Print Java Version
                command: 'java -version'
            - run:
                name: Print Node Version
                command: 'node -v'
            - run:
                name: Print NPM Version
                command: 'npm -v'
            - run:
                name: Install Node Modules
                command: 'npm install'
            - save_cache:
                paths:
                    - node
                    - node_modules
                    - ~/.gradle
                key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "package-lock.json" }}

            - run:
                name: Give Executable Power
                command: 'chmod +x gradlew'
            - run:
                name: Backend tests
                command: npm run ci:backend:test
            - run:
                name: Run Front End Tests
                command: npm run ci:frontend:test
